### ISSUE TITLE
TODO List 

### ISSUE THREAD

**Issue by kingjotaro** [kingjotaro/leaky-bucket#3]
- [x] Create basic API

- [x] Configure basic Redis settings

- [x]  Implement basic server-side counting

- [x]  Establish basic rate limiting for the API

- [x] Create Redis update on counting

- [x]  Create test plan

- [x]  Implement basic front-end with graphics

- [x] Update the readme
